### PR TITLE
Added CocoaPods support

### PR DESCRIPTION
**Pull request by pepicrft**
@blinker13 I was thinking about using your library but I wanted to use my :heart: dependency manager and your library didn't have support for it. I thought it could be a great idea to support it.

image

### CODE REVIEW

**Comment by blinker13** [comment]
You are kidding me...

**Comment by pepicrft** [comment]
You should seriously consider it @blinker13 . BTW universal configs are not compatible with Carthage. Really sad about that as well.

**Comment by blinker13** [comment]
Will look into that as soon as I have a working version. I'll add issues for all things considered for 1.0.0 at some point.

**Comment by pepicrft** [comment]
😢

**Pull request closed without merging**
